# Generated by Django 5.1 on 2024-08-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseinstance",
            name="semester",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="courseinstance",
            name="year",
            field=models.CharField(max_length=20),
        ),
    ]
